# install: conda env create -f environment.yaml
# update:  conda env update -f environment.yaml
name: torch_brain
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.8
  - pip
  - pip:
      - -e .[dev]
