# defaults used for training POYO
# this file needs to be combined with a model config and a dataset config

# Paths
data_root: /home/mila/p/pingsheng.li/scratch/brainsets_proc
log_dir: ./logs

# Transforms
train_transforms: []
eval_transforms: []

# Training
epochs: 1
batch_size: 16
eval_epochs: 1  # frequency for doing validation
eval_batch_size: null  # if null, will use batch_size
seed: 42  # use to set random seed
sanity_check_validation: false  # if true, will start the run with validation 

optim:
  base_lr: 3.125e-5  # scaled linearly by batch size
  weight_decay: 1e-4
  lr_decay_start: 0.5  # fraction of epochs before starting LR decay

# Logging
wandb:
  enable: true
  entity: null
  project: poyo-adp-win
  run_name: null
  log_model: false

# GPU and CPU
precision: 32
nodes: 1
gpus: 1
num_workers: 8

# Checkpointing
ckpt_path: /home/mila/p/pingsheng.li/scratch/poyo_adp_win_ckpt  # for resuming training, or loading a model during finetuning
