- selection:
  - brainset: allen_visual_coding_ophys_2016
    sessions:
    # 30 Drifting Gratings Holdout sessions from Azabou and Pan et al. 2025
    - "710504563"
    # - "623339221"
    # - "589441079"
    # - "603763073"
    # - "676503588"
    # - "652092676"
    # - "649409874"
    # - "671164733"
    # - "623347352"
    # - "649401936"
    # - "555042467"
    # - "646016204"
    # - "595273803"
    # - "539487468"
    # - "637669284"
    # - "539497234"
    # - "652737678"
    # - "654532828"
    # - "669233895"
    # - "560926639"
    # - "547388708"
    # - "595806300"
    # - "689388034"
    # - "649938038"
    # - "645689073"
    # - "510514474"
    # - "505695962"
    # - "512326618"
    # - "562122508"
    # - "653122667"
  config:
    sampling_intervals_modifier: |
      sampling_intervals = sampling_intervals & data.drifting_gratings.coalesce(0.3)
    multitask_readout:
      - readout_id: drifting_gratings_orientation
        timestamp_key: drifting_gratings.timestamps
        value_key: drifting_gratings.orientation_id
        metrics:
          - metric:
              _target_: torchmetrics.Accuracy
              task: multiclass
              num_classes: 8
      - readout_id: drifting_gratings_temporal_frequency
        timestamp_key: drifting_gratings.timestamps
        value_key: drifting_gratings.temporal_frequency_id
        metrics:
          - metric:
              _target_: torchmetrics.Accuracy
              task: multiclass
              num_classes: 5