- selection:
  - brainset: allen_visual_coding_ophys_2016
    sessions:
    - "501021421"
  config:
    sampling_intervals_modifier: |
      sampling_intervals = sampling_intervals & data.drifting_gratings.coalesce(0.3)
    multitask_readout:
      - readout_id: drifting_gratings_orientation
        timestamp_key: drifting_gratings.timestamps
        value_key: drifting_gratings.orientation_id
        metrics:
          - metric:
              _target_: torchmetrics.Accuracy
              task: multiclass
              num_classes: 8
      - readout_id: drifting_gratings_temporal_frequency
        timestamp_key: drifting_gratings.timestamps
        value_key: drifting_gratings.temporal_frequency_id
        metrics:
          - metric:
              _target_: torchmetrics.Accuracy
              task: multiclass
              num_classes: 5