- selection:
    - brainset: "ibl_brain_wide_map_2023"
      sessions:
        - "004d8fd5-41e7-4f1b-a45b-0d4ad76fe446"
        - "03063955-2523-47bd-ae57-f7489dd40f15"
        - "032ffcdf-7692-40b3-b9ff-8def1fc18b2e"
        - "037d75ca-c90a-43f2-aca6-e86611916779"
        - "04749a70-ac63-477d-8392-d4d529184fab"
        - "111c1762-7908-47e0-9f40-2f2ee55b6505"
        - "14127fdb-2e66-4823-b124-f49c128ba94d"
        - "15b69921-d471-4ded-8814-2adad954bcd8"
        - "16693458-0801-4d35-a3f1-9115c7e5acfd"
        - "1928bf72-2002-46a6-8930-728420402e01"
        - "196a2adf-ff83-49b2-823a-33f990049c2e"
        - "19b44992-d527-4a12-8bda-aa11379cb08c"
        - "19e66dc9-bf9f-430b-9d6a-acfa85de6fb7"
        - "1b715600-0cbc-442c-bd00-5b0ac2865de1"
        - "1ca83b26-30fc-4350-a616-c38b7d00d240"
        - "1d4a7bd6-296a-48b9-b20e-bd0ac80750a5"
        - "1e45d992-c356-40e1-9be1-a506d944896f"
        - "1eac875c-feaa-4a30-b148-059b954b11d8"
        - "1ec23a70-b94b-4e9c-a0df-8c2151da3761"
        - "21d21fc3-4201-4edc-802a-c67b61952548"
        - "239cdbb1-68e2-4eb0-91d8-ae5ae4001c7a"
        - "259927fd-7563-4b03-bc5d-17b4d0fa7a55"
        - "25d1920e-a2af-4b6c-9f2e-fc6c65576544"
        - "27ef44c0-acb2-4220-b776-477d0d5abd35"
        - "28338153-4113-485b-835b-91cb96d984f2"
        - "29a6def1-fc5c-4eea-ac48-47e9b053dcb5"
        - "2bdf206a-820f-402f-920a-9e86cd5388a4"
        - "2d5f6d81-38c4-4bdc-ac3c-302ea4d5f46e"
        - "30af8629-7b96-45b7-8778-374720ddbc5e"
        - "32d27583-56aa-4510-bc03-669036edad20"
        - "3537d970-f515-4786-853f-23de525e110f"
        - "35eeb752-8f4f-4040-9714-ba0f5b7ccdfe"
        - "3a3ea015-b5f4-4e8b-b189-9364d1fc7435"
        - "3bb54985-77b2-421d-9d1f-46185be51216"
        - "3e7ae7c0-fe8b-487c-9354-036236fa1010"
        - "4364a246-f8d7-4ce7-ba23-a098104b96e4"
        - "45ef6691-7b80-4a43-bd1a-85fc00851ae8"
        - "46794e05-3f6a-4d35-afb3-9165091a5a74"
        - "49368f16-de69-4647-9a7a-761e94517821"
        - "4ef13091-1bc8-4f32-9619-107bdf48540c"
        - "5139ce2c-7d52-44bf-8129-692d61dd6403"
        - "51e53aff-1d5d-4182-a684-aba783d50ae5"
        - "5285c561-80da-4563-8694-739da92e5dd0"
        - "5455a21c-1be7-4cae-ae8e-8853a8d5f55e"
        - "549caacc-3bd7-40f1-913d-e94141816547"
        - "5522ac4b-0e41-4c53-836a-aaa17e82b9eb"
        - "5569f363-0934-464e-9a5b-77c8e67791a1"
        - "56956777-dca5-468c-87cb-78150432cc57"
        - "5b44c40f-80f4-44fb-abfb-c7f19e27a6ca"
        - "5b49aca6-a6f4-4075-931a-617ad64c219c"
        - "5c0c560e-9e1f-45e9-b66e-e4ee7855be84"
        - "5ec72172-3901-4771-8777-6e9490ca51fc"
        - "63c70ae8-4dfb-418b-b21b-f0b1e5fba6c9"
        - "642c97ea-fe89-4ec9-8629-5e492ea4019d"
        - "64977c74-9c04-437a-9ea1-50386c4996db"
        - "66d98e6e-bcd9-4e78-8fbb-636f7e808b29"
        - "6713a4a7-faed-4df2-acab-ee4e63326f8d"
        - "671c7ea7-6726-4fbe-adeb-f89c2c8e489b"
        - "695a6073-eae0-49e0-bb0f-e9e57a9275b9"
        - "6a601cc5-7b79-4c75-b0e8-552246532f82"
        - "6bb5da8f-6858-4fdd-96d9-c34b3b841593"
        - "6c6983ef-7383-4989-9183-32b1a300d17a"
        - "6cbeead9-bb7a-40e1-8ccd-47ae60239654"
        - "6ed57216-498d-48a6-b48b-a243a34710ea"
        - "6f36868f-5cc1-450c-82fa-6b9829ce0cfe"
        - "71855308-7e54-41d7-a7a4-b042e78e3b4f"
        - "73918ae1-e4fd-4c18-b132-00cb555b1ad2"
        - "768a371d-7e88-47f8-bf21-4a6a6570dd6e"
        - "77e6dc6a-66ed-433c-b1a2-778c914f523c"
        - "781b35fd-e1f0-4d14-b2bb-95b7263082bb"
        - "7af49c00-63dd-4fed-b2e0-1b3bd945b20b"
        - "7cec9792-b8f9-4878-be7e-f08103dc0323"
        - "7eeb8423-49e6-4d40-ab6f-703d17af231a"
        - "810b1e07-009e-4ebe-930a-915e4cd8ece4"
        - "83d85891-bd75-4557-91b4-1cbb5f8bfc9d"
        - "87ad026d-5b95-4022-8d59-c260870d830f"
        - "8a3a0197-b40a-449f-be55-c00b23253bbf"
        - "8b1f4024-3d96-4ee7-95f9-8a1dfd4ce4ef"
        - "8c025071-c4f3-426c-9aed-f149e8f75b7b"
        - "8d316998-28c3-4265-b029-e2ca82375b2f"
        - "8db36de1-8f17-4446-b527-b5d91909b45a"
        - "90c61c38-b9fd-4cc3-9795-29160d2f8e55"
        - "90e524a2-aa63-47ce-b5b8-1b1941a1223a"
        - "90e74228-fd1a-482f-bd56-05dbad132861"
        - "91796ceb-e314-4859-9a1f-092f85cc846a"
        - "91e04f86-89df-4dec-a8f8-fa915c9a5f1a"
        - "934dd7a4-fbdc-459c-8830-04fe9033bc28"
        - "9468fa93-21ae-4984-955c-e8402e280c83"
        - "9b528ad0-4599-4a55-9148-96cc1d93fb24"
        - "9fcbd1a0-77e6-4c41-9428-eeaee74becd5"
        - "a2b9fbbe-79fc-4166-a16e-b307813a2f06"
        - "a66f1593-dafd-4982-9b66-f9554b6c86b5"
        - "a6fe44a8-07ab-49b8-81f9-e18575aa85cc"
        - "a7763417-e0d6-4f2a-aa55-e382fd9b5fb8"
        - "a7eba2cf-427f-4df9-879b-e53e962eae18"
        - "a82800ce-f4e3-4464-9b80-4c3d6fade333"
        - "a8a8af78-16de-4841-ab07-fde4b5281a03"
        - "a9138924-4395-4981-83d1-530f6ff7c8fc"
        - "aec5d3cc-4bb2-4349-80a9-0395b76f04e2"
        - "b887df2c-bb9c-44c9-a9c0-538da87b2cab"
        - "bb099402-fb31-4cfd-824e-1c97530a0875"
        - "bb8d9451-fdbd-4f46-b52e-9290e8f84d2e"
        - "bda2faf5-9563-4940-a80f-ce444259e47b"
        - "c16d3557-b2c1-4545-93d0-112ac0915d93"
        - "c46b8def-620d-4d70-9397-be5694255f73"
        - "c958919c-2e75-435d-845d-5b62190b520e"
        - "ca4ecb4c-4b60-4723-9b9e-2c54a6290a53"
        - "caa5dddc-9290-4e27-9f5e-575ba3598614"
        - "cae5cd75-55e5-4277-8db3-cf4d6c5ff918"
        - "d2832a38-27f6-452d-91d6-af72d794136c"
        - "d839491f-55d8-4cbe-a298-7839208ba12b"
        - "dc962048-89bb-4e6a-96a9-b062a2be1426"
        - "de905562-31c6-4c31-9ece-3ee87b97eab4"
        - "e2b845a1-e313-4a08-bc61-a5f662ed295e"
        - "e349a2e7-50a3-47ca-bc45-20d1899854ec"
        - "e56541a5-a6d5-4750-b1fe-f6b5257bfe7c"
        - "e5c75b62-6871-4135-b3d0-f6464c2d90c0"
        - "e6043c7d-8f6e-4b66-8309-2ec0abac0f79"
        - "eacc49a9-f3a1-49f1-b87f-0972f90ee837"
        - "ebc9392c-1ecb-4b4b-a545-4e3d70d23611"
        - "ebe2efe3-e8a1-451a-8947-76ef42427cc9"
        - "ee212778-3903-4f5b-ac4b-a72f22debf03"
        - "eebacd5a-7dcd-4ba6-9dff-ec2a4d2f19e0"
        - "f27e6cd6-cdd3-4524-b8e3-8146046e2a7d"
        - "f359281f-6941-4bfd-90d4-940be22ed3c3"
        - "f3ce3197-d534-4618-bf81-b687555d1883"
        - "f4eb56a4-8bf8-4bbc-a8f3-6e6535134bad"
        - "f56194bc-8215-4ae8-bc6a-89781ad8e050"
        - "f84045b0-ce09-4ace-9d11-5ea491620707"
        - "f88d4dd4-ccd7-400e-9035-fa00be3bcfa8"
        - "f9860a11-24d3-452e-ab95-39e199f20a93"
        - "f99ac31f-171b-4208-a55d-5644c0ad51c3"
        - "fa8ad50d-76f2-45fa-a52f-08fe3d942345"
        - "fc14c0d6-51cf-48ba-b326-56ed5a9420c3"
        - "fcd49e34-f07b-441c-b2ac-cb8c462ec5ac"
        - "ff96bfe1-d925-4553-94b5-bf8297adf259"
    multitask_readout:
      - readout_id: block_prior
        metrics:
          - metric:
              _target_: torchmetrics.Accuracy
              average: macro  # balanced accuracy
      - readout_id: choice
        metrics:
          - metric:
              _target_: torchmetrics.Accuracy
              average: macro  # balanced accuracy
      - readout_id: reward
        metrics:
          - metric:
              _target_: torchmetrics.Accuracy
              average: macro  # balanced accuracy
      - readout_id: stimulus_side
        metrics:
          - metric:
              _target_: torchmetrics.Accuracy
              average: macro  # balanced accuracy
      - readout_id: stimulus_contrast
        metrics:
          - metric:
              _target_: torchmetrics.Accuracy
              average: macro  # balanced accuracy
      - readout_id: whisker_motion_energy
        normalize_mean: 3.251806286016722
        normalize_std: 10.61425507976995
        metrics:
          - metric:
              _target_: torchmetrics.R2Score
          - metric:
              _target_: torchmetrics.MeanAbsoluteError
      - readout_id: wheel_speed
        normalize_mean: 0.01091022804128455
        normalize_std: 1.8591207977789714
        metrics:
          - metric:
              _target_: torchmetrics.R2Score
          - metric:
              _target_: torchmetrics.MeanAbsoluteError
      - readout_id: right_paw_v_xy
        normalize_mean:
          - 0.0051610683464418505
          - 0.0067826933132845
        normalize_std:
          - 13.50758467659989
          - 10.49881378227036
        metrics:
          - metric:
              _target_: torchmetrics.R2Score
          - metric:
              _target_: torchmetrics.MeanAbsoluteError
      - readout_id: left_paw_v_xy
        normalize_mean:
          - 0.0035585021889409
          - 0.0047933564866629
        normalize_std:
          - 10.867062419285507
          - 5.496618142559549
        metrics:
          - metric:
              _target_: torchmetrics.R2Score
          - metric:
              _target_: torchmetrics.MeanAbsoluteError
      - readout_id: licking
        normalize_mean: 0.
        normalize_std: 100.
        metrics:
          - metric:
              _target_: torchmetrics.R2Score
          - metric:
              _target_: torchmetrics.MeanAbsoluteError
