defaults:
  - model: poco.yaml
  - dataset: zappbench.yaml
  - _self_  # ensures current config overrides defaults


# defaults used for training POYO
# this file needs to be combined with a model config and a dataset config

# Paths
data_root: /vast/projects/dyer1/lab/shared/neural_data
log_dir: ./logs

# Transforms
eval_transforms: []

# Training
epochs: 1000
batch_size: 128
eval_epochs: 1  # frequency for doing validation
eval_batch_size: null  # if null, will use batch_size
seed: 42  # use to set random seed
sanity_check_validation: false  # if true, will start the run with validation

optim:
  base_lr: 3.125e-5  # scaled linearly by batch size
  weight_decay: 1e-4
  lr_decay_start: 0.5  # fraction of epochs before starting LR decay

# Logging
wandb:
  enable: false
  entity: null
  project: poCo
  run_name: null
  log_model: false

# GPU and CPU
precision: 32
nodes: 1
gpus: 1
num_workers: 4

# Checkpointing
ckpt_path: null  # for resuming training, or loading a model during finetuning



train_transforms:
  - _target_: torch_brain.transforms.PatchTokenize


context_window: null
forecast_window: null