defaults:
  - defaults.yaml
  - model: capoyo.yaml
  - dataset: capoyo_single_session.yaml
  - _self_

train_transforms:
  - _target_: torch_brain.transforms.UnitDropout
    max_units: 1000
    min_units: 60
    mode_units: 300
    peak: 4

wandb:
  run_name: capoyo_finetune

epochs: 100
ckpt_path: null  # Must specify path to model to finetune

# Num of epochs to freeze perceiver network while finetuning
# -1 => Keep frozen, i.e. perform Unit-identification
#  0 => Train everything
# >0 => Only train unit/session embeddings for first few epochs,
#       and then train everything
freeze_perceiver_until_epoch: 10