defaults:
  - defaults.yaml
  - model: capoyo.yaml
  - dataset: capoyo.yaml
  - _self_  # ensures current config overrides defaults

epochs: 2000
batch_size: 64

train_transforms:
  - _target_: torch_brain.transforms.UnitDropout
    field: "calcium_traces.df_over_f"
    min_units: 10
    mode_units: 50
    max_units: 300
    tail_right: 100

wandb:
  run_name: capoyo_full
  