defaults:
  - defaults.yaml
  - model: poyo_1.yaml
  - dataset: ibl_brain_wide_map_2023_finetune.yaml
  - _self_

train_transforms:
  - _target_: torch_brain.transforms.RegionSelection
    region: VISa
  - _target_: torch_brain.transforms.UnitDropout
    max_units: 1000
    min_units: 5
    mode_units: 20
    peak: 4
    
eval_transforms:
  - _target_: torch_brain.transforms.RegionSelection
    region: VISa

wandb:
  run_name: poyo-plus-ibl-finetune

ckpt_path: /u/mazabou/torch_brain/poyo-plus-ibl-bs4x-baselr6.25e-6-iblsampler-epoch=951.ckpt